
netty:
  server:
    port: 8080


aerospike:
  host: 192.168.99.100
  port: 3000
  
logging:
  file: logs/application-dev.log
  pattern:
    console: "%d{yyyy:MM:dd HH:mm:ss.SSS} %-5level %logger : %msg%n"
    file: "%d{yyyy:MM:dd HH:mm:ss.SSS} %-5level [%thread] %logger : %msg%n"
  level:
    root: INFO
    org.springframework: INFO
    com.mezzomedia: DEBUG
    org.hibernate: ERROR
spring:
  redis:
    host: 192.168.99.100
    port: 32768

mybatis:
    type-aliases-package: com.mezzomedia.core.model.domain
    configuration:
        map-underscore-to-camel-case: true
        use-generated-keys: true
        default-fetch-size: 100
        default-statement-timeout: 30
        default-executor-type: reuse
        auto-mapping-behavior: partial
    mapper-locations: classpath:com/mezzomedia/core/repository/*.xml
