
netty:
  server:
    port: 8080


aerospike:
  host: 192.168.99.100
  port: 3000
  
logging:
  file: logs/application-dev.log
  pattern:
    console: "%d{yyyy:MM:dd HH:mm:ss.SSS} %-5level %logger : %msg%n"
    file: "%d{yyyy:MM:dd HH:mm:ss.SSS} %-5level [%thread] %logger : %msg%n"
  level:
    root: INFO
    org.springframework: INFO
    com.mezzomedia: DEBUG
    org.hibernate: ERROR
spring:
  redis:
    host: 192.168.99.100
    port: 32768


    